### PR TITLE
Fix spelling mistake snIsRunnging() to snIsRunning()

### PR DESCRIPTION
**Pull request by ed-george**
Changed method `snIsRunnging` to be `snIsRunning`

### CODE REVIEW

**Comment by TheOneRing** [comment]
thanks :)

**Comment by ed-george** [comment]
No worries @TheOneRing. I have plenty of other changes to suggest - feel free to pull any you see fit when I get round to making some more pull requests. :)

**Comment by TheOneRing** [comment]
looks like you know what you are doing ;) I gave you acces to the repo as I probably won't continue the work on it but I think I could support you with a review from time to time :).
So feel free to just commit or open pr's

**Comment by ed-george** [comment]
:+1: Thanks a bunch

**Pull request merged**
